[theme]
base = "light"
primaryColor = "#FFCB05"
backgroundColor = "#F7F7F5"
secondaryBackgroundColor = "#EEEEF6"
textColor = "#1A1A2E"
font = "sans serif"

[server]
headless = true
runOnSave = true
maxUploadSize = 50
